### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by iamvery** [achedeuzot/ueberauth_auth0#213]
Thank you for the Auth0 strategy! I was pleased to find support for the `organization` parameter in https://github.com/achedeuzot/ueberauth_auth0/pull/191, but it doesn't look like the latest release (2.0.0) includes this change. Are you planning another release any time soon?

**Comment by achedeuzot** [comment]
Hi @iamvery 
Sorry for the huge delay but the package has finally been updated on hex.pm.
Cheers !

**Comment by iamvery** [comment]
Wonderful news! Thank you so much 👐
