### ISSUE TITLE
(Mix) Hex dependency resolution failed

### ISSUE THREAD

**Issue by ridzria** [achedeuzot/ueberauth_auth0#230]
Hi,
I'm new to phoenix and elixir... I'm trying to get the dependencies and when I run the following command, I get the error. Am I missing something? Still trying to figure it out what the actual error means?

`mix deps.get ueberauth_auth0`

Resolving Hex dependencies...
#Incompatibility<#Term<your app>, cause: {:conflict, #Incompatibility<#Term<ueberauth_auth0 >= 0.4.0>, cause: {:conflict, #Incompatibility<#Term<ueberauth_auth0 >= 0.4.0>, #Term<not oauth2 ~> 2.0>, cause: :dependency>, #Incompatibility<#Term<your app>, #Term<not oauth2 ~> 0.5>, cause: :dependency>}>, #Incompatibility<#Term<your app>, #Term<not ueberauth_auth0 ~> 2.1.0>, cause: :dependency>}>
Resolution completed in 0.822s
Because ueberauth_auth0 >= 0.4.0 depends on oauth2 ~> 2.0 and your app depends on oauth2 ~> 0.5, ueberauth_auth0 >= 0.4.0 is forbidden.
So, because your app depends on ueberauth_auth0 ~> 2.1.0, version solving failed.

**Comment by achedeuzot** [comment]
It looks like your issue comes from the fact that you're using oauth2 version 0.5 and this module depends on oauth2 version 2.0. You'll need to update your mix.exs file to use oauth2 version 2.0 or above.

You should find answers about this on stackoverflow or on the Elixir Forum ;)
