### ISSUE TITLE
Scopes from Auth0 are returned as a space-delimited list

### ISSUE THREAD

**Issue by adammohammed** [achedeuzot/ueberauth_auth0#232]
I noticed when trying to fetch the scopes using this strategy that the scopes in both the `/token` response and in the JWT from auth0 are space delimited, but the `credentials` object tries to `String.split/3` with comma as the delimiter.

For example, the response contains `"scope": "openid profile email"` and the credential scopes are: `credential.scopes = [ "openid profile email"]`, I think the expected result should be `credential.scopes = ["openid", "profile", "email"]`

**Comment by achedeuzot** [comment]
Indeed, good catch. There's a new fix coming up with the `id_token` JWT, I'll check this is also fixed with that change.

**Comment by achedeuzot** [comment]
Fixed by #233
