### ISSUE TITLE
Linking straight to Sign-Up tab

### ISSUE THREAD

**Issue by chrism2671** [achedeuzot/ueberauth_auth0#70]
This is working great, thank you!

I'm trying to create a link that goes straight to the 'Sign Up' tab on the Lock screen. I can that the lock.js implementation has an option for it: 

https://auth0.com/docs/libraries/lock/v11/configuration#initialscreen-string-

I have two questions:
1. Does the hosted lock we're using support options being sent to it? I can't see how to set them.
2. I think `handle_request!` prevents us from submitting any extra options.

Any ideas on how to approach would be great. I don't mind editing and submitting a PR if you can give me some guidance on the direction.

**Comment by achedeuzot** [comment]
Hi @chrism2671 ! 

I'm responding after a long long time, but better late than never ;) 

Do you still use lock ? Or have you passed to the new "Universal Login" widget recommended by auth0 ?

With the latest version of ueberauth_auth0 (0.7.0), I've added multiple params that can be passed to auth0 during the login phase. If you still need this feature, we could try and add the parameter required by auth0 to the current implementation.

Tell me what you think and we'll see how to include it :) 

Best regards,

**Comment by chrism2671** [comment]
We're still using hosted lock. I actually managed to hack it somehow, but I honestly can't remember how! Suffice to say, it's all working now, so I think it's safe to close this issue. Thanks so much for following up, it's much appreciated! :)
